# Generated by Django 3.1.4 on 2020-12-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=6)),
                ('term', models.CharField(max_length=5)),
                ('section', models.CharField(max_length=3)),
            ],
        ),
    ]
