# Generated by Django 3.1.5 on 2021-01-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outline',
            name='date_created',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='outline',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='outline',
            name='faculty',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='outline',
            name='number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='outline',
            name='section',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='outline',
            name='term',
            field=models.CharField(default='', max_length=100),
        ),
    ]
