# Generated by Django 3.1.4 on 2021-01-05 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outline',
            name='date_created',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=50)),
                ('outline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.outline')),
            ],
        ),
        migrations.CreateModel(
            name='GraduateAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=2)),
                ('attribute', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
                ('outline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.outline')),
            ],
        ),
        migrations.CreateModel(
            name='FinalGradeDetermination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.outline')),
            ],
        ),
        migrations.CreateModel(
            name='FinalGradeComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=50)),
                ('outcomes', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=4)),
                ('outline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.outline')),
            ],
        ),
        migrations.CreateModel(
            name='Examinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('outline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.outline')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(max_length=50)),
                ('credit', models.CharField(max_length=50)),
                ('calendar_reference', models.CharField(max_length=50)),
                ('outline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.outline')),
            ],
        ),
    ]
