# Generated by Django 3.1.5 on 2021-01-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210105_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='outline',
            name='description',
            field=models.CharField(default='description', max_length=50),
            preserve_default=False,
        ),
    ]
