# Generated by Django 3.1.5 on 2021-01-13 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_outline_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, null=True)),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.outline')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('office', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.outline')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=50, null=True)),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.outline')),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('year', models.CharField(max_length=50, null=True)),
                ('publisher', models.CharField(max_length=50, null=True)),
                ('requirement', models.CharField(max_length=50, null=True)),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.outline')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50, null=True)),
                ('days', models.CharField(max_length=50, null=True)),
                ('time', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.outline')),
            ],
        ),
        migrations.RemoveField(
            model_name='graduateattribute',
            name='outline',
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='attribute',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='level',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='examinations',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='FinalGradeDetermination',
        ),
        migrations.DeleteModel(
            name='GraduateAttribute',
        ),
    ]
