# Generated by Django 3.1.5 on 2021-01-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210113_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarinformation',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
